= Admin

== Objectives

* Centralize the information (= cartography) about "quickstarts/hands on lab" available to promote, educate our users around the   Microservices hype.
* Describe the procedure(s) to follow to :
** Submit Project's information : Name, description, tags = categories, owner, link to the repo : github, bitbucket, ..., project where it has been designed/realized and /or implemented, objectives & requirements
** Request to "upload" Project's with also the cartography of the project
* Define the conventions to follow when a new Project should be designed in order to stay consistent all together, to reduce maintenance time/costs as ideally a POC should be reusable for a later version of product and could become a quickstart (The holy grail ;-))
* Stage incoming Projects for people not having a git, bitbucket repo till we find their final destination
* Describe the criteria that we will use to accept, refuse Project request
* Produce documents around the recommnended design/patterns & practices
